name: Testing manual approve

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  PrintFirst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print
        run: echo "Hello World"

  ManualTrigger:
    needs: PrintFirst
    environment:
      name: approvers
    runs-on: ubuntu-latest
    steps:
      - name: manual approve
        run: echo "Manually Approved"

  PrintSecond:
    needs: ManualTrigger
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello Again!"
